angular.module('questionModule',[])
.controller('questionCtrl',['$scope',function ($scope) {
    $scope.isShow=false;
    $scope.isShow1=false;
    $scope.isShow2=false;
    $scope.isShow3=false;
    $scope.isShow4=false;
    $scope.isShow5=false;
    $scope.isShow6=false;
    $scope.isShow7=false;
    $scope.isShow8=false;
    $scope.isShow9=false;
    $scope.isShow10=false;
    $scope.isShow11=false;
    $scope.isShow12=false;
    $scope.isShow13=false;
    $scope.isShow14=false;
    $scope.isShow15=false;
    $scope.isShow16=false;
    $scope.isShow17=false;
    $scope.isShow18=false;
    $scope.isShow19=false;
    $scope.isShow20=false;
    $scope.isShow21=false;
    $scope.isShow22=false;
    $scope.isShow23=false;
    $scope.isShow24=false;
    $scope.isShow25=false;
    $scope.isShow26=false;
    $scope.isShow27=false;
    $scope.isShow28=false;

}])