angular.module('HomeModule',[])
.config(['$routeProvider',function($routeProvider){
	$routeProvider
	.when('/home',{
		templateUrl:'components/home/home.html',
		controller:'homeCtrl',
		css:'components/home/home.css',
	})
}])